# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: core-deployment
serviceName: core-service
appLabel: core-service
appName: core-service
hpaName: core-service-hpa

replicaCount: 1

image:
  repository: khanhquang/core.service
  tag: 1.0-SNAPSHOT

containerPort: 8181

service:
  type: ClusterIP
  port: 8181
  targetPort: 8181

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
eureka_instance_hostname_enabled: false
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: true
database_enabled: true
resources_enabled: false
redis_enabled: true

springDatasourceDatabase: core-service

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: ""

socket:
  enabled: false
  type: LoadBalancer
  port: 8082
  targetPort: 8184

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"