---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: default
  labels:
    app: core-service
spec:
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: com.backend.programming.learning.system/core.service:1.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/core-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "localdb"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
            - name: CONFIG_SERVER
              value: "http://config-server:9999"
            - name: EUREKA_SERVER
              value: "http://discovery-service:8761/eureka"
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: core-service
spec:
  selector:
    app: core-service
  ports:
    - name: core-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""
