---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak-deployment
  namespace: default
  labels:
    app: postgres-keycloak-deployment
spec:
  selector:
    matchLabels:
      app: postgres-keycloak-deployment
  template:
    metadata:
      labels:
        app: postgres-keycloak-deployment
    spec:
      containers:
        - name: postgres-keycloak-deployment
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_MAX_CONNECTIONS
              value: "200"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
spec:
  selector:
    app: postgres-keycloak-deployment
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: 5432
  type: LoadBalancer
---