---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: default
  labels:
    app: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: com.backend.programming.learning.system/config.server:1.0-SNAPSHOT
          env:
            - name: SERVER_PORT
              value: "9999"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.32.0.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: OTEL_METRICS_EXPORTER
            - name: OTEL_SERVICE_NAME
              value: config-server
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - name: config-server-port
      protocol: TCP
      port: 9999
  type: LoadBalancer
  loadBalancerIP: ""

