apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: default
  labels:
    app: discovery-service
spec:
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: com.backend.programming.learning.system/discovery.service:1.0-SNAPSHOT
          env:
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_APPLICATION_NAME
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_INSTANCE_HOSTNAME
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - name: discovery-service-port
      protocol: TCP
      port: 8761
  type: LoadBalancer
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: discovery-deployment-2
#  labels:
#    app: discovery-deployment-2
#spec:
#  selector:
#    matchLabels:
#      app: discovery-deployment-2
#  template:
#    metadata:
#      labels:
#        app: discovery-deployment-2
#    spec:
#      containers:
#        - name: discovery-service-2
#          image: com.backend.programming.learning.system/discovery.service:1.0-SNAPSHOT
#          resources:
#            limits:
#              cpu: "500m"
#              memory: "800Mi"
#            requests:
#              cpu: "200m"
#              memory: "256Mi"
#          env:
#            - name: LOGGING_LEVEL_ROOT
#              value: "info"
#            - name: LOG_APP-NAME
#              value: "discovery-service-2"
#            - name: SPRING_PROFILES_ACTIVE
#              value: "peer2"
#            - name: EUREKA_INSTANCE_HOSTNAME
#              value: "discovery-service-2"
#      volumes:
#        - name: discovery-service-logs
#          hostPath:
#            path: ./discovery-service-logs
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: discovery-service-2
#spec:
#  selector:
#    app: discovery-deployment-2
#  ports:
#    - protocol: TCP
#      port: 8762
#      name: discovery-service-2-port
#  type: LoadBalancer