---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: default
  labels:
    app: core-service
spec:
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: com.backend.programming.learning.system/core.service:1.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CORE_SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_BOOTSTRAP-SERVERS
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CONFIG_SERVER
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_SERVER
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: core-service
spec:
  selector:
    app: core-service
  ports:
    - name: core-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: com.backend.programming.learning.system/auth.service:1.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: AUTH_SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_BOOTSTRAP-SERVERS
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CONFIG_SERVER
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_SERVER
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: auth-service-port
      protocol: TCP
      port: 8182
      targetPort: 8182
  type: LoadBalancer
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-assessment-deployment
  labels:
    app: code-assessment-service
spec:
  selector:
    matchLabels:
      app: code-assessment-service
  template:
    metadata:
      labels:
        app: code-assessment-service
    spec:
      containers:
        - name: code-assessment-service
          image: com.backend.programming.learning.system/code.assessment.service:1.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CODE_ASSESSMENT_SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_BOOTSTRAP-SERVERS
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CONFIG_SERVER
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_SERVER
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: code-assessment-service
  namespace: default
  labels:
    app: code-assessment-service
spec:
  selector:
    app: code-assessment-service
  ports:
    - name: code-assessment-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  namespace: default
  labels:
    app: course-service
spec:
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: com.backend.programming.learning.system/course.service:1.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: COURSE_SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_BOOTSTRAP-SERVERS
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CONFIG_SERVER
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_SERVER
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: default
  labels:
    app: course-service
spec:
  selector:
    app: course-service
  ports:
    - name: course-service-port
      protocol: TCP
      port: 8184
    - name: socket-service-port
      protocol: TCP
      port: 8085
  type: LoadBalancer