apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: default
  labels:
    app: discovery-service
spec:
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: com.backend.programming.learning.system/discovery.service:1.0-SNAPSHOT
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_APPLICATION_NAME
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_INSTANCE_HOSTNAME
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - name: discovery-service-port
      protocol: TCP
      port: 8761
  type: ClusterIP